{
  dependencies: [
    HarmonyExportSpecifierDependency {
      _parentModule: [Circular *1],
      _parentDependenciesBlock: [Circular *1],
      _parentDependenciesBlockIndex: 0,
      weak: false,
      optional: false,
      _locSL: 1,
      _locSC: 0,
      _locEL: 3,
      _locEC: 1,
      _locI: undefined,
      _locN: undefined,
      _loc: [SourceLocation],
      id: 'iAmAImport',
      name: 'iAmAImport'
    }
  ],
  blocks: [],
  parent: undefined,
  type: 'javascript/auto',
  context: 'F:\\Programming\\WCL-Report-Component-TS-Template\\util',
  layer: null,
  needId: true,
  debugId: 1001,
  resolveOptions: {},
  factoryMeta: undefined,
  useSourceMap: false,
  useSimpleSourceMap: false,
  _warnings: undefined,
  _errors: undefined,
  buildMeta: {
    tsLoaderDefinitionFileVersions: [
      'definitions\\ComponentObject.d.ts@0',
      'definitions\\RpgLogs.d.ts@0',
      'node_modules\\@types\\eslint\\index.d.ts@0',
      'node_modules\\@types\\eslint\\helpers.d.ts@0',
      'node_modules\\@types\\estree\\index.d.ts@0',
      'node_modules\\@types\\json-schema\\index.d.ts@0',
      'node_modules\\@types\\eslint-scope\\index.d.ts@0',
      'node_modules\\@types\\node\\index.d.ts@0',
      'node_modules\\@types\\node\\assert.d.ts@0',
      'node_modules\\@types\\node\\assert\\strict.d.ts@0',
      'node_modules\\@types\\node\\globals.d.ts@0',
      'node_modules\\@types\\node\\worker_threads.d.ts@0',
      'node_modules\\@types\\node\\async_hooks.d.ts@0',
      'node_modules\\@types\\node\\buffer.d.ts@0',
      'node_modules\\@types\\node\\child_process.d.ts@0',
      'node_modules\\@types\\node\\cluster.d.ts@0',
      'node_modules\\@types\\node\\console.d.ts@0',
      'node_modules\\@types\\node\\constants.d.ts@0',
      'node_modules\\@types\\node\\crypto.d.ts@0',
      'node_modules\\@types\\node\\dgram.d.ts@0',
      'node_modules\\@types\\node\\diagnostics_channel.d.ts@0',
      'node_modules\\@types\\node\\dns.d.ts@0',
      'node_modules\\@types\\node\\dns\\promises.d.ts@0',
      'node_modules\\@types\\node\\domain.d.ts@0',
      'node_modules\\@types\\node\\dom-events.d.ts@0',
      'node_modules\\@types\\node\\events.d.ts@0',
      'node_modules\\@types\\node\\fs.d.ts@0',
      'node_modules\\@types\\node\\fs\\promises.d.ts@0',
      'node_modules\\@types\\node\\http.d.ts@0',
      'node_modules\\@types\\node\\http2.d.ts@0',
      'node_modules\\@types\\node\\https.d.ts@0',
      'node_modules\\@types\\node\\inspector.d.ts@0',
      'node_modules\\@types\\node\\module.d.ts@0',
      'node_modules\\@types\\node\\net.d.ts@0',
      'node_modules\\@types\\node\\os.d.ts@0',
      'node_modules\\@types\\node\\path.d.ts@0',
      'node_modules\\@types\\node\\perf_hooks.d.ts@0',
      'node_modules\\@types\\node\\process.d.ts@0',
      'node_modules\\@types\\node\\punycode.d.ts@0',
      'node_modules\\@types\\node\\querystring.d.ts@0',
      'node_modules\\@types\\node\\readline.d.ts@0',
      'node_modules\\@types\\node\\readline\\promises.d.ts@0',
      'node_modules\\@types\\node\\repl.d.ts@0',
      'node_modules\\@types\\node\\stream.d.ts@0',
      'node_modules\\@types\\node\\stream\\promises.d.ts@0',
      'node_modules\\@types\\node\\stream\\consumers.d.ts@0',
      'node_modules\\@types\\node\\stream\\web.d.ts@0',
      'node_modules\\@types\\node\\string_decoder.d.ts@0',
      'node_modules\\@types\\node\\test.d.ts@0',
      'node_modules\\@types\\node\\timers.d.ts@0',
      'node_modules\\@types\\node\\timers\\promises.d.ts@0',
      'node_modules\\@types\\node\\tls.d.ts@0',
      'node_modules\\@types\\node\\trace_events.d.ts@0',
      'node_modules\\@types\\node\\tty.d.ts@0',
      'node_modules\\@types\\node\\url.d.ts@0',
      'node_modules\\@types\\node\\util.d.ts@0',
      'node_modules\\@types\\node\\v8.d.ts@0',
      'node_modules\\@types\\node\\vm.d.ts@0',
      'node_modules\\@types\\node\\wasi.d.ts@0',
      'node_modules\\@types\\node\\zlib.d.ts@0',
      'node_modules\\@types\\node\\globals.global.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2016.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es5.d.ts@0',
      'node_modules\\typescript\\lib\\lib.decorators.d.ts@0',
      'node_modules\\typescript\\lib\\lib.decorators.legacy.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.core.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.collection.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.iterable.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.symbol.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.generator.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.promise.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.proxy.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.reflect.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.symbol.wellknown.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2016.array.include.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.object.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.sharedmemory.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.string.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.typedarrays.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.asynciterable.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.asyncgenerator.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.promise.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.regexp.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.array.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.object.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.string.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.symbol.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.bigint.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.date.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.number.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.promise.d.ts@0',
      ... 10 more items
    ],
    tsLoaderFileVersion: 0,
    exportsType: 'namespace',
    sideEffectFree: true
  },
  buildInfo: {
    cacheable: true,
    parsed: true,
    fileDependencies: undefined,
    contextDependencies: undefined,
    missingDependencies: undefined,
    buildDependencies: LazySet {
      _set: [Set],
      _toMerge: Set(0) {},
      _toDeepMerge: [],
      _needMerge: false,
      _deopt: false
    },
    valueDependencies: Map(1) { 'webpack/DefinePlugin_hash' => '9e418625' },
    hash: '8e31f7a0ebd0b5ca4fa7daea58315a35',
    assets: undefined,
    assetsInfo: undefined,
    strict: true,
    exportsArgument: '__webpack_exports__',
    topLevelDeclarations: Set(1) { 'iAmAImport' },
    snapshot: Snapshot {
      _flags: 4097,
      _cachedFileIterable: undefined,
      _cachedContextIterable: undefined,
      _cachedMissingIterable: undefined,
      startTime: 1682536097445,
      fileTimestamps: undefined,
      fileHashes: undefined,
      fileTshs: undefined,
      contextTimestamps: undefined,
      contextHashes: undefined,
      contextTshs: undefined,
      missingExistence: undefined,
      managedItemInfo: undefined,
      managedFiles: undefined,
      managedContexts: undefined,
      managedMissing: undefined,
      children: [Set]
    }
  },
  presentationalDependencies: [
    HarmonyCompatibilityDependency {
      _parentModule: undefined,
      _parentDependenciesBlock: undefined,
      _parentDependenciesBlockIndex: -1,
      weak: false,
      optional: false,
      _locSL: -1,
      _locSC: 0,
      _locEL: -1,
      _locEC: 0,
      _locI: -3,
      _locN: undefined,
      _loc: [Object]
    },
    HarmonyExportHeaderDependency {
      _parentModule: undefined,
      _parentDependenciesBlock: undefined,
      _parentDependenciesBlockIndex: -1,
      weak: false,
      optional: false,
      _locSL: 1,
      _locSC: 0,
      _locEL: 3,
      _locEC: 1,
      _locI: undefined,
      _locN: undefined,
      _loc: [SourceLocation],
      range: [Array],
      rangeStatement: [Array]
    }
  ],
  codeGenerationDependencies: undefined,
  request: 'F:\\Programming\\WCL-Report-Component-TS-Template\\node_modules\\ts-loader\\index.js!F:\\Programming\\WCL-Report-Component-TS-Template\\util\\someImport.ts',
  userRequest: 'F:\\Programming\\WCL-Report-Component-TS-Template\\util\\someImport.ts',
  rawRequest: '../util/someImport',
  binary: false,
  parser: JavascriptParser {
    hooks: {
      evaluateTypeof: [HookMap],
      evaluate: [HookMap],
      evaluateIdentifier: [HookMap],
      evaluateDefinedIdentifier: [HookMap],
      evaluateNewExpression: [HookMap],
      evaluateCallExpression: [HookMap],
      evaluateCallExpressionMember: [HookMap],
      isPure: [HookMap],
      preStatement: [Hook],
      blockPreStatement: [Hook],
      statement: [Hook],
      statementIf: [Hook],
      classExtendsExpression: [Hook],
      classBodyElement: [Hook],
      classBodyValue: [Hook],
      label: [HookMap],
      import: [Hook],
      importSpecifier: [Hook],
      export: [Hook],
      exportImport: [Hook],
      exportDeclaration: [Hook],
      exportExpression: [Hook],
      exportSpecifier: [Hook],
      exportImportSpecifier: [Hook],
      preDeclarator: [Hook],
      declarator: [Hook],
      varDeclaration: [HookMap],
      varDeclarationLet: [HookMap],
      varDeclarationConst: [HookMap],
      varDeclarationVar: [HookMap],
      pattern: [HookMap],
      canRename: [HookMap],
      rename: [HookMap],
      assign: [HookMap],
      assignMemberChain: [HookMap],
      typeof: [HookMap],
      importCall: [Hook],
      topLevelAwait: [Hook],
      call: [HookMap],
      callMemberChain: [HookMap],
      memberChainOfCallMemberChain: [HookMap],
      callMemberChainOfCallMemberChain: [HookMap],
      optionalChaining: [Hook],
      new: [HookMap],
      binaryExpression: [Hook],
      expression: [HookMap],
      expressionMemberChain: [HookMap],
      unhandledExpressionMemberChain: [HookMap],
      expressionConditionalOperator: [Hook],
      expressionLogicalOperator: [Hook],
      program: [Hook],
      finish: [Hook]
    },
    sourceType: 'auto',
    scope: undefined,
    state: undefined,
    comments: undefined,
    semicolons: undefined,
    statementPath: undefined,
    prevStatement: undefined,
    destructuringAssignmentProperties: undefined,
    currentTagData: undefined
  },
  parserOptions: undefined,
  generator: JavascriptGenerator {},
  generatorOptions: undefined,
  resource: 'F:\\Programming\\WCL-Report-Component-TS-Template\\util\\someImport.ts',
  resourceResolveData: {
    context: {
      issuer: 'F:\\Programming\\WCL-Report-Component-TS-Template\\components\\exampleComponent.ts',
      issuerLayer: null,
      compiler: undefined
    },
    path: 'F:\\Programming\\WCL-Report-Component-TS-Template\\util\\someImport.ts',
    request: undefined,
    query: '',
    fragment: '',
    module: false,
    directory: false,
    file: false,
    internal: false,
    fullySpecified: false,
    descriptionFilePath: 'F:\\Programming\\WCL-Report-Component-TS-Template\\package.json',
    descriptionFileData: {
      name: 'wcl-report-component-ts-template',
      version: '2.0.0',
      description: 'This is a template project, that allows you to write Warcraft Logs Report Components using TypeScript. ',
      main: 'index.js',
      scripts: [Object],
      keywords: [Array],
      author: 'Joschi-Grey',
      license: 'GPL-3.0-or-later',
      devDependencies: [Object]
    },
    descriptionFileRoot: 'F:\\Programming\\WCL-Report-Component-TS-Template',
    relativePath: './util/someImport.ts',
    __innerRequest_request: undefined,
    __innerRequest_relativePath: './util/someImport.ts',
    __innerRequest: './util/someImport.ts'
  },
  matchResource: undefined,
  loaders: [
    {
      loader: 'F:\\Programming\\WCL-Report-Component-TS-Template\\node_modules\\ts-loader\\index.js',
      type: undefined,
      options: undefined,
      ident: undefined
    }
  ],
  error: null,
  _source: RawSource {
    _valueIsBuffer: false,
    _value: 'export function iAmAImport() {\n' +
      `    return "I don't do anything though";\n` +
      '}\n',
    _valueAsBuffer: <Buffer 65 78 70 6f 72 74 20 66 75 6e 63 74 69 6f 6e 20 69 41 6d 41 49 6d 70 6f 72 74 28 29 20 7b 0a 20 20 20 20 72 65 74 75 72 6e 20 22 49 20 64 6f 6e 27 74 ... 24 more bytes>,
    _valueAsString: 'export function iAmAImport() {\n' +
      `    return "I don't do anything though";\n` +
      '}\n'
  },
  _sourceSizes: undefined,
  _sourceTypes: undefined,
  _lastSuccessfulBuildMeta: {
    tsLoaderDefinitionFileVersions: [
      'definitions\\ComponentObject.d.ts@0',
      'definitions\\RpgLogs.d.ts@0',
      'node_modules\\@types\\eslint\\index.d.ts@0',
      'node_modules\\@types\\eslint\\helpers.d.ts@0',
      'node_modules\\@types\\estree\\index.d.ts@0',
      'node_modules\\@types\\json-schema\\index.d.ts@0',
      'node_modules\\@types\\eslint-scope\\index.d.ts@0',
      'node_modules\\@types\\node\\index.d.ts@0',
      'node_modules\\@types\\node\\assert.d.ts@0',
      'node_modules\\@types\\node\\assert\\strict.d.ts@0',
      'node_modules\\@types\\node\\globals.d.ts@0',
      'node_modules\\@types\\node\\worker_threads.d.ts@0',
      'node_modules\\@types\\node\\async_hooks.d.ts@0',
      'node_modules\\@types\\node\\buffer.d.ts@0',
      'node_modules\\@types\\node\\child_process.d.ts@0',
      'node_modules\\@types\\node\\cluster.d.ts@0',
      'node_modules\\@types\\node\\console.d.ts@0',
      'node_modules\\@types\\node\\constants.d.ts@0',
      'node_modules\\@types\\node\\crypto.d.ts@0',
      'node_modules\\@types\\node\\dgram.d.ts@0',
      'node_modules\\@types\\node\\diagnostics_channel.d.ts@0',
      'node_modules\\@types\\node\\dns.d.ts@0',
      'node_modules\\@types\\node\\dns\\promises.d.ts@0',
      'node_modules\\@types\\node\\domain.d.ts@0',
      'node_modules\\@types\\node\\dom-events.d.ts@0',
      'node_modules\\@types\\node\\events.d.ts@0',
      'node_modules\\@types\\node\\fs.d.ts@0',
      'node_modules\\@types\\node\\fs\\promises.d.ts@0',
      'node_modules\\@types\\node\\http.d.ts@0',
      'node_modules\\@types\\node\\http2.d.ts@0',
      'node_modules\\@types\\node\\https.d.ts@0',
      'node_modules\\@types\\node\\inspector.d.ts@0',
      'node_modules\\@types\\node\\module.d.ts@0',
      'node_modules\\@types\\node\\net.d.ts@0',
      'node_modules\\@types\\node\\os.d.ts@0',
      'node_modules\\@types\\node\\path.d.ts@0',
      'node_modules\\@types\\node\\perf_hooks.d.ts@0',
      'node_modules\\@types\\node\\process.d.ts@0',
      'node_modules\\@types\\node\\punycode.d.ts@0',
      'node_modules\\@types\\node\\querystring.d.ts@0',
      'node_modules\\@types\\node\\readline.d.ts@0',
      'node_modules\\@types\\node\\readline\\promises.d.ts@0',
      'node_modules\\@types\\node\\repl.d.ts@0',
      'node_modules\\@types\\node\\stream.d.ts@0',
      'node_modules\\@types\\node\\stream\\promises.d.ts@0',
      'node_modules\\@types\\node\\stream\\consumers.d.ts@0',
      'node_modules\\@types\\node\\stream\\web.d.ts@0',
      'node_modules\\@types\\node\\string_decoder.d.ts@0',
      'node_modules\\@types\\node\\test.d.ts@0',
      'node_modules\\@types\\node\\timers.d.ts@0',
      'node_modules\\@types\\node\\timers\\promises.d.ts@0',
      'node_modules\\@types\\node\\tls.d.ts@0',
      'node_modules\\@types\\node\\trace_events.d.ts@0',
      'node_modules\\@types\\node\\tty.d.ts@0',
      'node_modules\\@types\\node\\url.d.ts@0',
      'node_modules\\@types\\node\\util.d.ts@0',
      'node_modules\\@types\\node\\v8.d.ts@0',
      'node_modules\\@types\\node\\vm.d.ts@0',
      'node_modules\\@types\\node\\wasi.d.ts@0',
      'node_modules\\@types\\node\\zlib.d.ts@0',
      'node_modules\\@types\\node\\globals.global.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2016.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es5.d.ts@0',
      'node_modules\\typescript\\lib\\lib.decorators.d.ts@0',
      'node_modules\\typescript\\lib\\lib.decorators.legacy.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.core.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.collection.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.iterable.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.symbol.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.generator.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.promise.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.proxy.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.reflect.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.symbol.wellknown.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2016.array.include.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.object.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.sharedmemory.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.string.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.typedarrays.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.asynciterable.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.asyncgenerator.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.promise.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.regexp.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.array.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.object.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.string.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.symbol.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.bigint.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.date.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.number.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.promise.d.ts@0',
      ... 10 more items
    ],
    tsLoaderFileVersion: 0,
    exportsType: 'namespace',
    sideEffectFree: true
  },
  _forceBuild: false,
  _isEvaluatingSideEffects: false,
  _addedSideEffectsBailout: undefined,
  _codeGeneratorData: Map(0) {},
  _ast: null
}018.regexp.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.array.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.object.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.string.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.symbol.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.bigint.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.date.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.number.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.promise.d.ts@0',
      ... 10 more items
    ],
    tsLoaderFileVersion: 0,
    exportsType: 'namespace',
    sideEffectFree: true
  },
  _forceBuild: false,
  _isEvaluatingSideEffects: false,
  _addedSideEffectsBailout: undefined,
  _codeGeneratorData: Map(0) {},
  _ast: null
}ode_modules\\@types\\node\\globals.global.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2016.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es5.d.ts@0',
      'node_modules\\typescript\\lib\\lib.decorators.d.ts@0',
      'node_modules\\typescript\\lib\\lib.decorators.legacy.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.core.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.collection.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.iterable.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.symbol.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.generator.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.promise.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.proxy.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.reflect.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2015.symbol.wellknown.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2016.array.include.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.object.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.sharedmemory.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.string.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2017.typedarrays.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.asynciterable.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.asyncgenerator.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.promise.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.regexp.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2018.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.array.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.object.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.string.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.symbol.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2019.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.bigint.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.intl.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.date.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.number.d.ts@0',
      'node_modules\\typescript\\lib\\lib.es2020.promise.d.ts@0',
      ... 13 more items
    ],
    tsLoaderFileVersion: 0,
    exportsType: 'namespace'
  },
  _forceBuild: false,
  _isEvaluatingSideEffects: false,
  _addedSideEffectsBailout: undefined,
  _codeGeneratorData: Map(0) {},
  _ast: null
}